Main.cpp
const Scalar PRETO
Define escalares de cores
Referenced by Contorno.
const Scalar BRANCO
Representação da cor Preta
Referenced by Contorno.
const Scalar AMARELO
Representação da cor Branca
Referenced by contador.
const Scalar VERDE
Representação da cor Amarela
Referenced by main.
const Scalar VERMELHO
Representação da cor Verde
Referenced by blobInfo, contador, main.
int contEsq
Representação da cor Vermelha Inicializa os contadores de carros na parte esqueda e direita, respectivamente
Referenced by contador, main.
int contDir
Referenced by main.
double distPontos(Point ponto1, Point ponto2)
Calcula a distância entre os pontos
Referenced by verificaBlob.
void insereBlob(Blob &blobAtual, vector< Blob > &blobsExistentes, int &intIndex)
Define os parâmetros do blob atual no vetor de blobs existentes
References Blob::contornoAtual, Blob::quadro, Blob::posicoesCentro, Blob::diagonal, Blob::proporcao.
Referenced by verificaBlob.
void novoBlob(Blob &blobAtual, vector< Blob > &blobsExistentes)
Adiciona um novo blob no vetor de blobs existentes
References Blob::blobAtualNovo.
Referenced by verificaBlob.
void verificaBlob(vector< Blob > &blobsExistentes, vector< Blob > &blobsAtuais)
Verifica se o blob atual já existe no vetor de blobs
References distPontos, insereBlob, novoBlob.
Referenced by main.
void Contorno(Size imageSize, vector< vector< Point >> contornos, string strImageName)
Desenha o contorno dos blobs
References PRETO, BRANCO.
Referenced by main.
void Contorno(Size imageSize, vector< Blob > blobsExistentes, string strImageName)
Desenha o contorno dos blobs
References PRETO, BRANCO.
bool cruzouLinhaDir(vector< Blob > &blobsExistentes, int &linhaHor, int &contDir)
Verifica se o veículo cruzou a linha da direita
Referenced by main.
bool cruzouLinhaEsq(vector< Blob > &blobsExistentes, int &linhaHor, int &contEsq)
Verifica se o veículo cruzou a linha da esquerda
Referenced by main.
void blobInfo(vector< Blob > &blobsExistentes, Mat &cloneFrame2)
Imprime as informações do blob na tela
References VERMELHO.
Referenced by main.
void contador(int &contDir, Mat &cloneFrame2)
Imprime o contador na imagem
References VERMELHO, contEsq, AMARELO.
Referenced by main.
int main(void)
References Contorno, Blob::quadro, Blob::proporcao, Blob::diagonal, Blob::contornoAtual, verificaBlob, blobInfo, cruzouLinhaDir, contDir, cruzouLinhaEsq, contEsq, VERDE, VERMELHO, contador.